parameters:
#    home.example.class: SocialNetwork\Bundle\HomeBundle\Example

services:
#    home.example:
#        class: %home.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
